### ISSUE TITLE
Using again as an override for 'do'

### ISSUE THREAD

**Issue by ravl1084** [nthorne/todo.txt-cli-again-addon#12]
Hi,
I often find myself using 'do' instead of 'again' for tasks that have an again attribute in them, therefore not creating the next instance of the task.

Is there a way to have 'again' ignore tasks that don't have an again tag and just mark them done, so 'again' can be a drop in replacement for 'do'?

**Comment by nthorne** [comment]
Hi @ravl1084! Sorry about the late response; I'ts a bit hectic at work at the moment, but that does sound like a good idea. I'll look into that when things clear up a bit.

**Comment by nthorne** [comment]
... the default behavior is to add tasks again regardless of again/ tags. One option would perhaps be to make that be configurable; if e.g. `TODO_NO_AGAIN_IF_NOT_TAGGED` is set, then again would act as a `do` on tasks without a again tag. Does that sound like it'd work for you?

**Comment by ravl1084** [comment]
That would work perfectly, thank you!

**Comment by nthorne** [comment]
Hi, I pushed pull request #15, which should introduce this feature. Do you have the possibility to check it out, to see if it is implemented as you wished, before I merge it?

**Comment by ravl1084** [comment]
I tested it and it seems to be working as expected, thank you!
