### ISSUE TITLE
Creation and completion dates are not handled correctly

### ISSUE THREAD

**Issue by ravl1084** [nthorne/todo.txt-cli-again-addon#13]
When completing a recurring task with again, the new instance of the task gets the two dates from the originating task prepended to it:

~~~
~$ t again 17 
17 x 2018-03-14 2018-02-14 pay cable @laptop +bills t:2018-03-14 rec:+1m due:2018-03-14                                                                               
TODO: 17 marked as done.
x 2018-03-14 2018-02-14 pay cable @laptop +bills t:2018-03-14 rec:+1m due:2018-03-14                                                                                  
TODO: /home/rav/Nextcloud/Todo/todo.txt archived.
48 (B) 2018-03-14 2018-02-14 pay cable @laptop +bills t:2018-04-14 rec:+1m due:2018-04-14
TODO: 48 added.
~~~

**Comment by nthorne** [comment]
Are you running the latest version of again? This sounds like the issue fixed by @juzim in pull request #11; also, I don't see this issue when trying with your sample session. Here's what my session looks like:

    [nix-shell:~/src/again/test]$ todo.sh again 1
    1 x 2018-03-17 2018-02-14 pay cable @laptop +bills t:2018-03-14 rec:+1m due:2018-03-14
    TODO: 1 marked as done.
    x 2018-03-17 2018-02-14 pay cable @laptop +bills t:2018-03-14 rec:+1m due:2018-03-14
    TODO: /home/nthorne/tmp/todo/todo.txt archived.
    1 2018-03-17 pay cable @laptop +bills t:2018-03-17 rec:+1m due:2018-03-17
    TODO: 1 added.

**Comment by ravl1084** [comment]
I confirmed that I have the latest version, including pull request #11, did a fresh pull from the repo.

Here's another example:

~~~
~$ t ls @home
48 (A) 2018-03-07 Take out recycling @home t:2018-03-20 rec:+2w due:2018-03-20
35 (A) 2018-03-13 Take out trash @home t:2018-03-20 rec:+1w due:2018-03-20
--
TODO: 6 of 48 tasks shown
rav@titan:~$ t again 48
48 x 2018-03-21 2018-03-07 Take out recycling @home t:2018-03-20 rec:+2w due:2018-03-20
TODO: 48 marked as done.
x 2018-03-21 2018-03-07 Take out recycling @home t:2018-03-20 rec:+2w due:2018-03-20
TODO: /home/rav/Nextcloud/Todo/todo.txt archived.
48 (A) 2018-03-21 2018-03-07 Take out recycling @home t:2018-04-03 rec:+2w due:2018-04-03
TODO: 48 added.
~~~

**Comment by nthorne** [comment]
Iinteresting.. Which version of todo.txt are you running; are you using any other plugins etc, and what does your configuration look like? Also, which operating system are you using?

**Comment by ravl1084** [comment]
I have todo.txt v2.10 on Ubuntu 16.04. The only other plugin I'm using is [outline](https://github.com/samuelsnyder/outline-todo.txt) .

**Comment by nthorne** [comment]
... weird. Could you add the following line at line 19 (right after the licensing information) of the again script:

set -x

and then attach the output from a session similar to the ones you've demonstrated above to this thread (e.g. run `todo.sh again 48 > again.log` and then attach the resulting again.log)?

**Comment by ravl1084** [comment]
Here is the log, I suspect it has to do with the priority.
[again.log](https://github.com/nthorne/todo.txt-cli-again-addon/files/1915508/again.log)

**Comment by nthorne** [comment]
.. do you think that you could give the FixingDoubleDates branch a spin and see if it fixes your issue; seems to be working fine on my end, but just to make sure?

e.g.
    cd <AGAIN PATH>
   git pull
   git checkout FixingDoubleDates

and then

    git checkout -

to jump back to the master branch once you've tested it out.

**Comment by ravl1084** [comment]
I tested it and it's working well. Thank you!
