### ISSUE TITLE
Make again work on rec tags as well

### ISSUE THREAD

**Issue by nthorne** [nthorne/todo.txt-cli-again-addon#14]
Since I use SimpleTask on my Android phone, I set the rec tag for recurring tasks; again should be updated to be able to recognize these tags as well (perhaps controllable with an environment variable).

Also, _if_ again supports this feature, then it needs to support the extensions as well. More specifically, the SimpleTask specific `b` recurrence modifier (*b*usiness day) needs to be supported. Also, investigate if there are any more secret-sauce modifiers that should be supported. Also make sure that any introduced features are backwards compatible as to not introduce any regression.

**Comment by munkee** [comment]
Does 898dc4f44818935a34f0412c878088b1aba8a5f5 handle this?

**Comment by nthorne** [comment]
Hi @munkee ,

Not entirely; If you look at <https://github.com/mpcjanssen/simpletask-android/blob/master/app/src/main/assets/index.en.md#Extensions> you'll notice that SimpleTask e.g. supports the b recurrence modifier, so this task is a reminder to add the missing features. This issue is a bit poorly formulated, though; I'll go ahead and clearify a bit. Thanks!

**Comment by munkee** [comment]
I'm actually working on the logic for the b recurrence pattern as well. I don't use it currently for any of my todos, but it's the only thing missing from being compatible with [Swift todo app](http://swiftodoapp.com/)

So far I've just been working the logic out on paper because I haven't figured out your code yet. 

    START_DOW=`date -d "$ORIGINAL" +"%u"` # Find the Day Of Week of the start date (Monday=1)
    DAYS_TO_MOVE = ADJUST_NUM+2*( (START_DOW + ADJUST_NUM - 1)/5)

Then you should just be able to use the regular days adjust code.

**Comment by nthorne** [comment]
Looks pretty solid to me; neat and tidy, and I really like the thorough testing. Thank you, @munkee

**Comment by nthorne** [comment]
.. I added you to the list of contributors, hope that is ok with you.
