### ISSUE TITLE
Again detects AGAIN_TAG even when it appears not followed by a colon.

### ISSUE THREAD

**Issue by tgdnt** [nthorne/todo.txt-cli-again-addon#16]
Hi, I use `again` as my `do`, with the TODO_NO_AGAIN_IF_NOT_TAGGED option on. When you have a task with text that includes the AGAIN_TAG as part of a word, again detects it, triggering itself even though the pattern appears not as a key/value pair.

Example:
if I have my AGAIN_TAG set to "rec", when I have a task that includes the word "reconcile", it gets re-added automatically, which it shouldn't since I have the TODO_NO_AGAIN_IF_NOT_TAGGED option on.

**Comment by tgdnt** [comment]
I have submitted #17 to fix this.

**Comment by nthorne** [comment]
Ah, but of course. Nicely done there, @tgdnt 
Thank you!
