### ISSUE TITLE
Add examples to README.md

### ISSUE THREAD

**Issue by jbrc** [nthorne/todo.txt-cli-again-addon#4]
The Usage section of README.md is good, but I think an Examples section would also be helpful. I didn't immediately grasp the difference between the DAYS and the +DAYS syntax.

I'm imagining something that starts with an example recurring task, then runs 'todo.sh again' a few times with different arguments, showing the output from todo.sh after each step.

I intend to work on this, but just wanted to open an issue to encourage feedback before I get too far.

**Comment by nthorne** [comment]
Sounds like a good idea. It is kinda hard for me to know what is missing in the documentation, since I already know how things work, so any external feedback is more than welcome.
