### ISSUE TITLE
RFC: Support time periods other than days (months, years)

### ISSUE THREAD

**Issue by jbrc** [nthorne/todo.txt-cli-again-addon#5]
I use a lot of tasks that recur once a month, once every three months, once a year, etc. The underlying date implementations support syntax for other time periods, like months and years.

GNU implementation
$ date -d "2015-08-29 3 months" +%Y-%m-%d
2015-11-29

BSD implementation
$ date -j -v3m -f %Y-%m-%d 2015-08-29 +%Y-%m-%d
2015-11-29 (untested; according to documentation)

I think it would make sense to add support for this to again.

**Why not use just use the number of days in a month/year?**
Some recurring tasks, like "pay rent," are always due on the same day of the month. Since months have different numbers of days, I'd have to think too hard each month about whether to add 28 (February), 29 (leap year February), 30 (some months), or 31 (most months). I'd rather just type "todo.sh again N 1m" to increment the month but leave the day alone.

**Problem with late dates**
What should be the result of (2015-08-31 + 1 month)? 2015-09-31 is not a valid date. BSD will decrement the day number and return 2015-09-30. Over time, this will result in later days (29, 30, 31) drifting to 30 (short months) and eventually to 28 (February). GNU will always increment by 31 days if the day number would not be valid in the next month, which in this case returns 2015-10-01.

I personally like the BSD behavior better; I don't mind as much if my dates are early by a couple of days, but missing a task deadline is bad. So, again might have to build in some extra smarts to provide the BSD behavior (using awk/sed?) even when the GNU implementation is present.

**Comment by nthorne** [comment]
Sounds like a good feature; one could keep the default behaviour for days, but add support for stepping months or years.

I agree that the BSD behaviour is more desirable when stepping months. A bit trickier to get that one working, but nothing impossible.

**Comment by jbrc** [comment]
I'm working on implementing this feature right now. For more efficient testing, I found it useful to move some of the helper functions (adjust_date, determine_date_version, and a couple of others) to a separate file which I named againHelpers.sh. I also created a new unitTests.sh file that sources againHelpers.sh and makes several calls to adjust_date, without having to setup dummy tasks in test\sample.txt. My plan is for again to also source againHelpers.sh. Does this violate a design goal of keeping all of the add-on code in a single file?

If it does, my backup plan was to add a flag in again (something like AGAIN_TEST_IN_PROGRESS) and place most of the execution inside of an if block guarded by this flag. testAgain.sh could set the flag (to disable execution) then source again. If you would like to stick to a single file, what are your thoughts regarding this approach?

**Comment by nthorne** [comment]
I hate code duplication as much as developer, and I most certainly do not have some hidden single-file agenda, so if refactoring things into a utility file makes development and testing easier, I'm all for it.

One alternate solution to all of this would, I guess, be to detect modify again in such a way that it detects if it is sourced or not, and provide different behaviour in that case, but I'm not sure if there exists a portable way to detect that.
