### ISSUE TITLE
Annotate tasks with recurrence period

### ISSUE THREAD

**Issue by jbrc** [nthorne/todo.txt-cli-again-addon#6]
Many of my tasks always recur with the same interval. To save me extra manual work each time a task recurs, I'd rather annotate the task with an interval, then call again with no extra arguments. again would scan the line, notice the interval, and use that as the DAYS argument.

Something like this:
$ todo.sh list
5 a weekly task t:2015-08-10 due:2015-08-11 again:+7
$ todo.sh again 5
\# Mark task 5 done.
\# Create new task as:
6 a weekly task t:2015-08-17 due:2015-08-18 again:+7

If no again tag is present, the current "no arguments" behavior remains the same.

**Comment by nthorne** [comment]
Sounds like a neat feature to have, and it should not be too hard to implement.

**Comment by nthorne** [comment]
Pull request merged. Updated test and documentation.
